### ISSUE TITLE
导入暴力猴后学达云网页不显示课节

### ISSUE THREAD

**Issue by 125540947** [tankririri/ok99ok99.com#1]
导入暴力猴后学达云网页不显示课节[](url)
![screenshot-gxejbx ok99ok99 com-2024 051](https://github.com/zhangminghao1989/ok99ok99.com/assets/38803156/18c7d30f-fea5-4ffe-9f62-d33fd228faeb)
最好来一个使用教程

**Comment by zhangminghao1989** [comment]
请测试关闭暴力猴之后是否能正常上课。
提供系统版本、浏览器版本，是否开启广告拦截插件？

**Comment by 125540947** [comment]
> 请测试关闭暴力猴之后是否能正常上课。 提供系统版本、浏览器版本，是否开启广告拦截插件？

系统为win11
浏览器为谷歌浏览器
装有卡巴斯基
没装广告拦截插件

**Comment by zhangminghao1989** [comment]
请测试关闭暴力猴之后是否能正常上课。

卡巴斯基有没有开启广告拦截功能？

按F12打开开发者工具，查看网络日志，是否所有页面都正常载入了。

**Comment by 125540947** [comment]
> 请测试关闭暴力猴之后是否能正常上课。
> 
> 卡巴斯基实验室开启广告拦截功能？
> 
> 按F12打开开发者工具，查看网络日志，所有页面是否都正常载入了。

卡巴斯基已经推出
![screenshot-gxejbx ok99ok99 com-2024 0512](https://github.com/zhangminghao1989/ok99ok99.com/assets/38803156/fb53c542-9166-4545-ae04-e50f33c6e762)
你看一下

**Comment by zhangminghao1989** [comment]
你先把浏览器的所有插件都关掉，确认问题的原因是插件还是网站本身的问题

**Comment by 125540947** [comment]
> 你把浏览器的所有插件都关掉，确认问题插件还是网站本身问题

我用擅改猴可以用了，暴力猴不行，都是一样的插件，
能用就行，能添加中途出现的人脸认证确认码

**Comment by zhangminghao1989** [comment]
人脸认证会自动点击确认的，如果不起作用需要你提供账号密码才能修复。

**Comment by 125540947** [comment]
人脸认证会自动点击确认的，如果不起作用需要你提供账号密码才能修复。
Originally posted by @zhangminghao1989 in https://github.com/zhangminghao1989/ok99ok99.com/issues/1#issuecomment-2134697874

![screenshot-gxejbx ok99ok99 com-2024 0125](https://github.com/zhangminghao1989/ok99ok99.com/assets/38803156/3b50e4a6-2841-4c09-a245-f6eaefe00e0f)

期待做出考试答案题库接口。https://tiku.tk.icu/login.html

**Comment by zhangminghao1989** [comment]
这个人脸认证应该是需要用手机验证的，无法跳过。

**Comment by 125540947** [comment]
> 本人脸面认证应该需要用手机验证的，无法跳过。

手动的话直接点确定，人脸识别，点确定就行了

**Comment by zhangminghao1989** [comment]
需提供账号密码
